### ISSUE TITLE
Task Manager

### ISSUE THREAD

**Issue by JeffreyFitzsimmons** [JeffreyFitzsimmons/Homework#1]
### Description 
This issue is meant to help me keep track of homework tasks that need to be completed and of those that are completed.

### Tasks

- [x] Task 1: Set up Overleaf and LaTeX
- [x] Task 2: Complete Git Branching Game
- [x] Task 3: Create Github Issue and Task Tracker

### Progress Made
- Total Tasks: 3
- Completed Tasks: 3
- Tasks Left To Complete: 0
